// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCapdaBoo1Pb99WiqeKkJKeFGcUpGyjpNY',
    appId: '1:528717084824:web:409673bd1011f4214538ed',
    messagingSenderId: '528717084824',
    projectId: 'signinflutter-44532',
    authDomain: 'signinflutter-44532.firebaseapp.com',
    storageBucket: 'signinflutter-44532.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuvx1cHhPnAkenr6qXy9GRhG5oYVI5zvI',
    appId: '1:528717084824:android:28e951b9c3a11d494538ed',
    messagingSenderId: '528717084824',
    projectId: 'signinflutter-44532',
    storageBucket: 'signinflutter-44532.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXA7-wYyTlwhg_9LdzIL2TzMoxWu_t-DA',
    appId: '1:528717084824:ios:cfb9d08255c136ba4538ed',
    messagingSenderId: '528717084824',
    projectId: 'signinflutter-44532',
    storageBucket: 'signinflutter-44532.appspot.com',
    iosBundleId: 'com.example.seProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXA7-wYyTlwhg_9LdzIL2TzMoxWu_t-DA',
    appId: '1:528717084824:ios:e5ab9f5c4f58c0184538ed',
    messagingSenderId: '528717084824',
    projectId: 'signinflutter-44532',
    storageBucket: 'signinflutter-44532.appspot.com',
    iosBundleId: 'com.example.seProject.RunnerTests',
  );
}
